name: {{ cookiecutter.repo_name }}-env
dependencies:
{%- if cookiecutter.require_boost_headers == "yes" %}
  - boost-cpp
{%- endif %}

{%- if cookiecutter.require_yaml_cpp == "yes" %}
  - yaml-cpp
{%- endif %}

{%- if cookiecutter.git_tracking == "yes" %}
  - git
# required for commitizen
  - nodejs
{%- endif %}

{%- if cookiecutter.linting_support_for_CXX == "yes" %}
  - pre-commit
  - cppcheck
  - sarcasm::clang-format
{%- endif %}

  - libtool
  - automake
  - autoconf
  - make>=4.2
  - gxx_linux-64>=8.2.0

{%- if cookiecutter.unit_test_framework == "google" %}
  - gtest
  - gmock
{%- endif %}
